# Site settings
title: Adithyan B
facebook_username: adhithyan.adhi.50159
name: Adithyan B
designation: Game Developer

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/AdhithAdhi
 - title: LinkedIn
   url: https://www.linkedin.com/in/adhithyan-b-794b27165/
#Any buzzword skills you want to include
skills:
 - Unity3d
 - .NET Framework
 - C#
 - C++
 - Java
 - Visual Studio
 - Object-Oriented Programming (OOP)
 - SQL
 - Blender
 - Game Programming
 - Vulnerability
 - Cryptography
 - Linux
 - Network and System Security
 - Cyber Security
 - Shell Scripting

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2016
   subject: Cyber Forensic
   school: MG University, School of Technology and Applied Science, Pathanamthitta
   
 - level: Master of Science (M.Sc.)
   date: 2020
   subject: Cyber Forensic
   school: MG University, School of Technology and Applied Science, Pathanamthitta

#List of interesting Github repo/projects to include - optional
github:
 - AdhithAdhi/DefendTheInvaders
 - AdhithAdhi/Maths-Infinity

#Stackoverflow flair is optional
contactways:
   profileurl: https://www.linkedin.com/in/adhithyan-b-794b27165/
   flairimageurl: https://media-exp1.licdn.com/dms/image/C4E03AQG0PIoy0D9izA/profile-displayphoto-shrink_400_400/0/1549435635180?e=1628726400&v=beta&t=aqY3dRjciqC1HOzWN60oVv-schM5d8DCzBTZIsQxCv8
   email: adhithadhi007@gmail.com
   phone: +91 9847242413
   
intro: |

  Accomplished Game Developer with expert game design skills, and game development proficiency seeks a creative role at a studio with a demonstrable focus and passion for crafting jaw-dropping online and mobile play experiences.<br/><br/>
  I may not have a working experience but am ready to secure a position as a Game Developer in a fast growing gaming industry that creates and develops high tech games where skills and expertise can maximize potential growth.
  I enjoy building interesting projects, with a good project Management focus.<br/><br/>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>C#(C-Sharp)</strong>: My current role uses C# as the primary language and have been building applications in C# for the last two years. I am familiar with a range of C# dotNet libraries.<br/><br/>
   <strong>Shell Script</strong>: I am experienced in Linux Shell Coding as part of my course.<br/><br/>
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks as part of my course.<br/><br/>
   <strong>CryptoGraphy</strong>: I know various cryptographic methods like AES, DES, Tripple DES, RSA, etc as part of my course.<br/><br/>
   <strong>PhP</strong>: I am experienced in a variety of PhP API’s and frameworks as part of my course.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client/server side technology, having used jQuery, Bootstrap, Asp.Net Server pages and database implementation. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, Xamarin, Windows/Linux Command Line applications, Google Firebase, Android OS Development, UI/UX GUI Designs, Etc.  <br/><br/>
   

theme: jekyll-theme-merlot
