# Site settings
title: Adithyan B
name: Adithyan B
designation: Cyber Security
linkedin_username: adhithyan-b-794b27165
github_username: AdhithAdhi
reddit_username: 
facebook_username: adhithyan.adhi.50159

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/AdhithAdhi
 - title: LinkedIn
   url: https://www.linkedin.com/in/adithyan-b-794b27165/

#intro or profile
intro: |

  An experienced cyber security professional who  can protect and secure computer systems and data. We are dedicated to  providing security implementation support  including in-depth analysis,  planning and preparation.<br/><br/>

#Any buzzword skills you want to include
skills:
 - name: Cyber Security
   value: 90
 - name: Security Tools
   value: 90
 - name: Security Analysis
   value: 80
 - name: Network Security
   value: 70
 - name: IT Security
   value: 70
 - name: Information Security
   value: 100
 - name: Incident Management
   value: 100
 - name: Incident Response
   value: 100
 - name: Customer Service
   value: 100
 - name: Decision Making
   value: 100
 - name: Fast Learner
   value: 100
 - name: Teamwork
   value: 100
 - name: Adaptability
   value: 100
 - name: Leadership Skills
   value: 100
 - name: Ability to Multitask
   value: 100
 - name: Time Management
   value: 100
 - name: Ability to Work Under Pressure
   value: 100
 - name: Flexibility and Adaptability
   value: 100
 - name: Critical thinking and problem solving
   value: 100

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json


#Projects is required
project:
 - p_title: Secure Banking using CaRP and Rabin Cryptosystem - 
   date: Mar, 2019
   discription: Many security primitives are based on hard mathematical problems. Using hard AI problems for security is emerging as an exciting new paradigm, but has been underexplored. In this paper, we present a new security primitive based on hard AI problems, namely, a novel family of graphical password systems built on top of Captcha technology, which we call Captcha as graphical passwords (CaRP). CaRP is both a Captcha and a graphical password scheme. CaRP is not a panacea, but it offers reasonable security and usability and appears to fit well with some practical applications for improving online security

 - p_title: Anti-Phishing Website
   date: Oct, 2018
   discription: There are e- banking websites who ask users to provide sensitive data such as username, password or credit card details etc. often for malicious reasons. This type of e-banking website is known as a phishing website. In order to detect and predict e-banking phishing websites, we proposed an intelligent, flexible and effective system that is based on using classification Data mining algorithm.We implemented classification algorithm and techniques to extract the phishing data sets criteria to classify their legitimacy

#Work experience is required
work:
 - j_title: Cyber Secrity Engineer
   employer: DxC Technology
   date: Sep, 2021 - Present
   city: Bangalore
   discription: <ul><li>Configuration-Tweaking, Management, and Maintenance of Security-Related Tools and Applications, such as Intrusion Detection/Prevention Systems, EDR Systems, Email Content Filter, and Vulnerability Scanners such as <ul><li>Nessus Professional </li><li>Force-point Content Gateway/Proxy </li><li>Force-point Email Security</li></ul> </li><li>A working understanding of and expertise with enterprise platforms for endpoint security tools, such as <ul><li>Trend Micro Apex-one </li><li>Trend Micro Deep Security </li><li>Trend Micro Apex Central  </li></ul></li><li>Planning, adjusting, controlling, overseeing, and improving security procedures to secure the data, systems, and networks of the firm. </li><li>As part of the current status of the comprehensive security programme, administer and implement the required standards, processes, and procedural modifications. </li><li>Analysing logs as part of the security and network troubleshooting process. </li><li>Addressing any system or network security flaws. </li><li>Enabling the proper security controls to secure the infrastructure and data of the enterprise. </li><li>SLA procedures, incident and change management Testing for and locating system and network vulnerabilities. </li><li>Daily administrative tasks, reporting, and interaction with the organization's key divisions and stakeholders Keeping up with the most recent malware and security risks. </li><li>Distribute knowledge throughout the staff and hold training sessions to improve others' skills. </li><li>Generating and evaluating reports for various threats across various OS platforms. </li><li>Recognising and analysing the assault pattern using EDR. </li><li>Proficiency in creating numerous reports, dashboards, and documentation. </li><li>Create, deliver, and follow up on actionable items and dependencies for other teams. </li><li>Utilizing predetermined action plans and deadlines with accountable endpoint Engineers and other business units, track the correction of vulnerabilities. </li><li>Notifying End-Clients the various measures needed to prevent system compromise. </li><li>Ensuring that security technologies are operating at their peak efficiency and that security events are discovered in time for correction.</li><li> Work with vendors to provide product updates, issue repairs, and relationship management.</li></ul>

#Education is required
education:
 - level: Master of Science (M.Sc.)
   date: 2020-2022
   subject: Cyber Forensic
   school: School of Technology and Applied Science (STAS), Pathanamthitta
   university: MG University

 - level: Bachelor of Science (B.Sc.)
   date: 2016-2019
   subject: Cyber Forensic
   school: School of Technology and Applied Science (STAS), Pathanamthitta
   university: MG University
   

#Languages is required
languages:
 - lang: Malayalam
   value: 100

 - lang: English
   value: 80

#Activities is optional
activitiy:
 - name: Cyberdome at Kerala Police
   date: 2020 - Present
   city: Trivandrum

 - name: National Service Scheme
   date: Jul, 2016 - Apr, 2019
   city: 


#Reference is optional
reference:
 - name: 
   details: Available upon request
   
#Stackoverflow flair is optional
contactways:
   profileurl: https://www.linkedin.com/in/adithyan-b-794b27165/
   flairimageurl: https://raw.githubusercontent.com/AdhithAdhi/AdhithAdhi.github.io/master/img/1645098093496.jpg
   email: adhithadhi007@gmail.com
   phone: +91 7907222956
   

theme: jekyll-theme-merlot
