# Site settings
title: Adithyan B
name: Adithyan B
designation: Game Developer
linkedin_username: adhithyan-b-794b27165
github_username: AdhithAdhi
reddit_username: Maximum-Gas-1448
facebook_username: adhithyan.adhi.50159

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/AdhithAdhi
 - title: LinkedIn
   url: https://www.linkedin.com/in/adithyan-b-794b27165/

#Any buzzword skills you want to include
skills:
 - name: Unity3d
   value: 90
 - name: C#
   value: 90
 - name: .NET Framework
   value: 80
 - name: SQL
   value: 70
 - name: C++
   value: 60
 - name: Java
   value: 60
 - name: Blender
   value: 60

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
work:
 - j_title: Cyber Secrity Engineer
   employer: DxC Technology
   date: Sep, 2021 - Present
   city: Bangalore
   discription:     Configuration-Tweaking, Management, and Maintenance of Security-Related Tools and Applications, such as Intrusion Detection/Prevention Systems, EDR Systems, Email Content Filter, and Vulnerability Scanners such as 
    Nessus Professional
    Force-point Content Gateway/Proxy
    Force-point Email Security
    A working understanding of and expertise with enterprise platforms for endpoint security tools, such as 
    Trend Micro Apex-one
    Trend Micro Deep Security
    Trend Micro Apex Central
    Planning, adjusting, controlling, overseeing, and improving security procedures to secure the data, systems, and networks of the firm.
    As part of the current status of the comprehensive security programme, administer and implement the required standards, processes, and procedural modifications.
    Analysing logs as part of the security and network troubleshooting process.
    Addressing any system or network security flaws.
    Enabling the proper security controls to secure the infrastructure and data of the enterprise.
    SLA procedures, incident and change management
    Testing for and locating system and network vulnerabilities.
    Daily administrative tasks, reporting, and interaction with the organization's key divisions and stakeholders
    Keeping up with the most recent malware and security risks.
    Distribute knowledge throughout the staff and hold training sessions to improve others' skills. 
    Generating and evaluating reports for various threats across various OS platforms.
    Recognising and analysing the assault pattern using EDR.
    Proficiency in creating numerous reports, dashboards, and documentation.
    Create, deliver, and follow up on actionable items and dependencies for other teams.
    Utilizing predetermined action plans and deadlines with accountable endpoint Engineers and other business units, track the correction of vulnerabilities.
    Notifying End-Clients the various measures needed to prevent system compromise.
    Ensuring that security technologies are operating at their peak efficiency and that security events are discovered in time for correction.
    Work with vendors to provide product updates, issue repairs, and relationship management.
   

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2016-2019
   subject: Cyber Forensic
   school: School of Technology and Applied Science (STAS), Pathanamthitta
   university: MG University
   
 - level: Master of Science (M.Sc.)
   date: 2020-2022
   subject: Cyber Forensic
   school: School of Technology and Applied Science (STAS), Pathanamthitta
   university: MG University

#Languages is required
languages:
 - lang: Malayalam
   value: 5

 - lang: English
   value: 4

#Stackoverflow flair is optional
contactways:
   profileurl: https://www.linkedin.com/in/adithyan-b-794b27165/
   flairimageurl: https://raw.githubusercontent.com/AdhithAdhi/AdhithAdhi.github.io/master/img/1645098093496.jpg
   email: adhithadhi007@gmail.com
   phone: +91 7907222956
   
intro: |

  An experienced cyber security professional who  can protect and secure computer systems and data. We are dedicated to  providing security implementation support  including in-depth analysis,  planning and preparation.<br/><br/>


theme: jekyll-theme-merlot
